### ISSUE TITLE
1 line task clipping

### ISSUE THREAD

**Issue by alexvarha** [jujoco/twitch-multitask-task-list-overlay#13]
As a streamer I'd like to have a setting allowing me to chose whether to clip tasks taking longer than 1 line, to better control how my cards and tasks look for the viewers

<img width="337" alt="iCTXui8z08" src="https://github.com/jujoco/twitch-multitask-task-list-overlay/assets/125912906/fe204548-6fc8-43a5-8dbf-783c97981c8e">

**Comment by jujoco** [comment]
while keeping to the minimalistic design, what would you suggest? 

Side-scrolling would be a bit too much as the main list already scrolls vertically.

**Comment by alexvarha** [comment]
can the task's line be wrapped within the width + padding of the card?

**Comment by jujoco** [comment]
I will provide you with code and instructions on how you can disable the text ellipses..

a useful thing about the Ellipses is it discourages task spammers from flooding your tasklist with long text..   (example:  1 task with 40 words would make that 1 User's card very long.)  Also, it promoted equality among viewers since every task takes up the same amount of space.  1️⃣ = 1️⃣

**Comment by alexvarha** [comment]
That is a valid argument. Maybe the middle ground is to allow a 2 line per task and/or 140 character limit?

**Comment by jujoco** [comment]
upon further consideration, this request is out of the scope of this project direction. 
close issue request.
